[package]
name = "libchess"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.99", default-features = false }

[features]
default = ["alloc"]
alloc = []

[dev-dependencies]
proptest = "1.7.0"
